// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kqhxkfuvfetcheptqznx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtxaHhrZnV2ZmV0Y2hlcHRxem54Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3NzgxMjksImV4cCI6MjA2NTM1NDEyOX0.n5Rz1HtKSLFe3dQZnBKyOdBU4qAU95O68cHxldXKN60";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);